spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      auto-offset-reset: earliest
server:
  port: 8080